name: king_of_lateral_thinking_2
description: This is literal thinking game for one updated from previous version.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.9+10

environment:
  sdk: ">=2.15.0-134.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^0.14.0+4
  audioplayers: ^0.20.1
  awesome_dialog: ^2.1.2
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.11
  package_info: ^2.0.2
  url_launcher: ^6.0.17
  app_review: ^2.1.1+1
  flutter_sliding_tutorial: ^1.1.2
  google_mobile_ads: ^1.0.1
  firebase_core: ^1.10.6
  firebase_remote_config: ^1.0.3
  firebase_database: ^9.0.4
  convex_bottom_bar: ^3.0.0
  intl: ^ 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: "assets/icons/small-logo.png"
  color: "000000"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/images/background/
    - assets/images/list_tile/
    - assets/images/lecture/

  fonts:
    - family: NotoSerifJP
      fonts:
        - asset: assets/fonts/NotoSerifJP-Regular.otf
        - asset: assets/fonts/NotoSerifJP-Bold.otf
          weight: 700
    - family: KaiseiOpti
      fonts:
        - asset: assets/fonts/KaiseiOpti-Regular.ttf
        - asset: assets/fonts/KaiseiOpti-Bold.ttf
          weight: 700
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
    - family: ZenAntiqueSoft
      fonts:
        - asset: assets/fonts/ZenAntiqueSoft-Regular.ttf
    - family: YujiSyuku
      fonts:
        - asset: assets/fonts/YujiSyuku-Regular.ttf
    - family: SawarabiGothic
      fonts:
        - asset: assets/fonts/SawarabiGothic-Regular.ttf
